services:
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "4001:4001"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  db:
    # on utilise l'image officiel de postgres
    image: postgres:15
    # permet à la db de redémarrer en cas d'erreur/pb
    restart: always
    # "healthcheck" exécute des tests et renvoie l'état de santé de la DB (boolean).
    healthcheck:
      # les commandes à executer pour run le health check.
      test: ["CMD-SHELL", "pg_isready -d aera_project_db -U asma"]
      # le temps entre chaque execution du health chceck
      interval: 5s
      # Le temps max que doit prendre l'execution du health check
      timeout: 5s
      # Le nombre max d'essai consécutif. Après ça, le container est considéré comme unhealthy
      retries: 10
    env_file:
      - backend/.env
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: aera_project_db
      POSTGRES_USER: asma
      POSTGRES_PASSWORD: aera_project_password
      DB_HOST: db
    # permet de ne pas perdre les données à chaque arrêt.
    volumes: 
      - aera_project_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000

volumes:
  aera_project_db:

#     Résumé en 1 phrase
# services.db.volumes = j’utilise le volume
# volumes: (en bas) = je crée le volume
